version: '3.8'

services:
  postgresql-main:
    image: 'postgres'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user
      - POSTGRES_DB=tarea1
    volumes:
      - ./postgres/schema.sql:/docker-entrypoint-initdb.d/create_schema.sql
      - ./postgres/airports.sql:/docker-entrypoint-initdb.d/data.sql

  redis-master:
    image: 'redis'
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  
  redis-replica1:
    image: 'redis'
    ports:
      - '6380:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    command: ["redis-server", "--slaveof", "redis-master", "6379"]

  redis-replica2:
    image: 'redis'
    ports:
      - '6381:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    command: ["redis-server", "--slaveof", "redis-master", "6379"]