version: '3.8'

services:
  postgresql-main:
    image: 'postgres'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user
      - POSTGRES_DB=tarea1
    volumes:
      - ./postgres/schema.sql:/docker-entrypoint-initdb.d/create_schema.sql
      - ./postgres/airports.sql:/docker-entrypoint-initdb.d/data.sql

  redis1:
    image: 'redis'
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  redis2:
    image: 'redis'
    ports:
      - '6380:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  redis3:
    image: 'redis'
    ports:
      - '6381:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes