insert into AIRPORTS (code, name) values ('KIR', 'Kerry Airport');
insert into AIRPORTS (code, name) values ('0', 'EMBRAER - Unidade Gavião Peixoto Airport');
insert into AIRPORTS (code, name) values ('SCV', 'Suceava Stefan cel Mare Airport');
insert into AIRPORTS (code, name) values ('URG', 'Rubem Berta Airport');
insert into AIRPORTS (code, name) values ('-', 'Vejrø');
insert into AIRPORTS (code, name) values ('THZ', 'Tahoua Airport');
insert into AIRPORTS (code, name) values ('BOA', 'Boma Airport');
insert into AIRPORTS (code, name) values ('ADR', 'Robert F Swinnie Airport');
insert into AIRPORTS (code, name) values ('ANQ', 'Tri State Steuben County Airport');
insert into AIRPORTS (code, name) values ('KDN', 'Ndende Airport');
insert into AIRPORTS (code, name) values ('YMV', 'Mary River Aerodrome');
insert into AIRPORTS (code, name) values ('GST', 'Gustavus Airport');
insert into AIRPORTS (code, name) values ('TOC', 'Toccoa Airport - R.G. Letourneau Field');
insert into AIRPORTS (code, name) values ('ZBK', 'Žabljak Airport');
insert into AIRPORTS (code, name) values ('GWE', 'Thornhill Air Base');
insert into AIRPORTS (code, name) values ('VJB', 'Xai-Xai Airport');
insert into AIRPORTS (code, name) values ('YDU', 'Kasba Lake Airport');
insert into AIRPORTS (code, name) values ('CPS', 'St Louis Downtown Airport');
insert into AIRPORTS (code, name) values ('BCH', 'Cakung Airport');
insert into AIRPORTS (code, name) values ('OSO', 'Osborne Mine Airport');
insert into AIRPORTS (code, name) values ('AYT', 'Antalya International Airport');
insert into AIRPORTS (code, name) values ('YWR', 'White River Seaplane Base');
insert into AIRPORTS (code, name) values ('ZIA', 'Zhukovsky International Airport');
insert into AIRPORTS (code, name) values ('AMM', 'Queen Alia International Airport');
insert into AIRPORTS (code, name) values ('TIX', 'Space Coast Regional Airport');
insert into AIRPORTS (code, name) values ('ALX', 'Thomas C Russell Field');
insert into AIRPORTS (code, name) values ('SHW', 'Sharurah Airport');
insert into AIRPORTS (code, name) values ('BDZ', 'Baindoung Airport');
insert into AIRPORTS (code, name) values ('AIP', 'Adampur Airport');
insert into AIRPORTS (code, name) values ('ILK', 'Atsinanana Airport');
insert into AIRPORTS (code, name) values ('LMC', 'El Refugio/La Macarena Airport');
insert into AIRPORTS (code, name) values ('HHR', 'Jack Northrop Field Hawthorne Municipal Airport');
insert into AIRPORTS (code, name) values ('AMJ', 'Cirilo Queiróz Airport');
insert into AIRPORTS (code, name) values ('IGO', 'Chigorodó Airport');
insert into AIRPORTS (code, name) values ('NKL', 'N''Kolo-Fuma Airport');
insert into AIRPORTS (code, name) values ('ALP', 'Aleppo International Airport');
insert into AIRPORTS (code, name) values ('GRY', 'Grímsey Airport');
insert into AIRPORTS (code, name) values ('GOH', 'Godthaab / Nuuk Airport');
insert into AIRPORTS (code, name) values ('JUR', 'Jurien Bay Airport');
insert into AIRPORTS (code, name) values ('VRU', 'Vryburg Airport');
insert into AIRPORTS (code, name) values ('AFD', 'Port Alfred Airport');
insert into AIRPORTS (code, name) values ('NLA', 'Simon Mwansa Kapwepwe International Airport');
insert into AIRPORTS (code, name) values ('POS', 'Piarco International Airport');
insert into AIRPORTS (code, name) values ('NOZ', 'Spichenkovo Airport');
insert into AIRPORTS (code, name) values ('POX', 'Pontoise - Cormeilles-en-Vexin Airport');
insert into AIRPORTS (code, name) values ('NYM', 'Nadym Airport');
insert into AIRPORTS (code, name) values ('BLL', 'Billund Airport');
insert into AIRPORTS (code, name) values ('CCB', 'Cable Airport');
insert into AIRPORTS (code, name) values ('ELL', 'Ellisras Matimba Airport');
insert into AIRPORTS (code, name) values ('ZQW', 'Zweibrücken Airport');
insert into AIRPORTS (code, name) values ('FLG', 'Flagstaff Pulliam Airport');
insert into AIRPORTS (code, name) values ('WAD', 'Andriamena Airport');
insert into AIRPORTS (code, name) values ('OTP', 'Henri Coandă International Airport');
insert into AIRPORTS (code, name) values ('0', 'Bandeirantes Airport');
insert into AIRPORTS (code, name) values ('UMY', 'Sumy Airport');
insert into AIRPORTS (code, name) values ('BDC', 'Barra do Corda Airport');
insert into AIRPORTS (code, name) values ('PUJ', 'Punta Cana International Airport');
insert into AIRPORTS (code, name) values ('MIE', 'Delaware County Johnson Field');
insert into AIRPORTS (code, name) values ('CRC', 'Santa Ana Airport');
insert into AIRPORTS (code, name) values ('SPD', 'Saidpur Airport');
insert into AIRPORTS (code, name) values ('YYD', 'Smithers Airport');
insert into AIRPORTS (code, name) values ('RNE', 'Roanne-Renaison Airport');
insert into AIRPORTS (code, name) values ('IEJ', 'Ie Jima Airport');
insert into AIRPORTS (code, name) values ('TGR', 'Touggourt Sidi Madhi Airport');
insert into AIRPORTS (code, name) values ('OLC', 'Senadora Eunice Micheles Airport');
insert into AIRPORTS (code, name) values ('GSH', 'Goshen Municipal Airport');
insert into AIRPORTS (code, name) values ('EBL', 'Erbil International Airport');
insert into AIRPORTS (code, name) values ('XTL', 'Tadoule Lake Airport');
insert into AIRPORTS (code, name) values ('LMO', 'RAF Lossiemouth');
insert into AIRPORTS (code, name) values ('JSY', 'Syros Airport');
insert into AIRPORTS (code, name) values ('UKB', 'Kobe Airport');
insert into AIRPORTS (code, name) values ('IVI', 'Viveros Island Airport');
insert into AIRPORTS (code, name) values ('PAZ', 'El Tajín National Airport');
insert into AIRPORTS (code, name) values ('SRI', 'Temindung Airport');
insert into AIRPORTS (code, name) values ('KKQ', 'Krasnoselkup Airport');
insert into AIRPORTS (code, name) values ('IDB', 'Idre Airport');
insert into AIRPORTS (code, name) values ('PUF', 'Pau Pyrénées Airport');
insert into AIRPORTS (code, name) values ('ANX', 'Andøya Airport');
insert into AIRPORTS (code, name) values ('YBF', 'Bamfield Seaplane Base');
insert into AIRPORTS (code, name) values ('INH', 'Inhambane Airport');
insert into AIRPORTS (code, name) values ('UJN', 'Uljin Airport');
insert into AIRPORTS (code, name) values ('CUP', 'General Francisco Bermúdez Airport');
insert into AIRPORTS (code, name) values ('GBT', 'Gorgan Airport');
insert into AIRPORTS (code, name) values ('XFN', 'Xiangyang Liuji Airport');
insert into AIRPORTS (code, name) values ('NKG', 'Nanjing Lukou Airport');
insert into AIRPORTS (code, name) values ('MUY', 'Mouyondzi Airport');
insert into AIRPORTS (code, name) values ('SZZ', 'Szczecin-Goleniów "Solidarność" Airport');
insert into AIRPORTS (code, name) values ('SNR', 'Saint-Nazaire-Montoir Airport');
insert into AIRPORTS (code, name) values ('RRG', 'Sir Charles Gaetan Duval Airport');
insert into AIRPORTS (code, name) values ('ANR', 'Antwerp International Airport (Deurne)');
insert into AIRPORTS (code, name) values ('JCM', 'Jacobina Airport');
insert into AIRPORTS (code, name) values ('BWN', 'Brunei International Airport');
insert into AIRPORTS (code, name) values ('TDR', 'Theodore Airport');
insert into AIRPORTS (code, name) values ('YJA', 'Jasper Airport');
insert into AIRPORTS (code, name) values ('RME', 'Griffiss International Airport');
insert into AIRPORTS (code, name) values ('SYO', 'Shonai Airport');
insert into AIRPORTS (code, name) values ('NNX', 'Nunukan Airport');
insert into AIRPORTS (code, name) values ('GFL', 'Floyd Bennett Memorial Airport');
insert into AIRPORTS (code, name) values ('SJD', 'Los Cabos International Airport');
insert into AIRPORTS (code, name) values ('ILA', 'Illaga Airport');
insert into AIRPORTS (code, name) values ('FOG', 'Foggia "Gino Lisa" Airport');
insert into AIRPORTS (code, name) values ('YXT', 'Northwest Regional Airport Terrace-Kitimat');
insert into AIRPORTS (code, name) values ('YZV', 'Sept-Îles Airport');
insert into AIRPORTS (code, name) values ('XQP', 'Quepos Managua Airport');
insert into AIRPORTS (code, name) values ('SCS', 'Scatsta Airport');
insert into AIRPORTS (code, name) values ('TXG', 'Taichung Airport');
insert into AIRPORTS (code, name) values ('OIL', 'Splane Memorial Airport');
insert into AIRPORTS (code, name) values ('EMD', 'Emerald Airport');
insert into AIRPORTS (code, name) values ('PLD', 'Playa Samara/Carrillo Airport');
insert into AIRPORTS (code, name) values ('KXR', 'Karoola Airport');
insert into AIRPORTS (code, name) values ('LTL', 'Lastourville Airport');
insert into AIRPORTS (code, name) values ('VTF', 'Vatulele Airport');
insert into AIRPORTS (code, name) values ('SFU', 'Safia Airport');
insert into AIRPORTS (code, name) values ('CZW', 'Częstochowa-Rudniki');
insert into AIRPORTS (code, name) values ('WGO', 'Winchester Regional Airport');
insert into AIRPORTS (code, name) values ('OAX', 'Xoxocotlán International Airport');
insert into AIRPORTS (code, name) values ('YYW', 'Armstrong Airport');
insert into AIRPORTS (code, name) values ('FRZ', 'Fritzlar Airport');
insert into AIRPORTS (code, name) values ('ULI', 'Ulithi Airport');
insert into AIRPORTS (code, name) values ('SJM', 'San Juan Airport');
insert into AIRPORTS (code, name) values ('HTH', 'Hawthorne Industrial Airport');
insert into AIRPORTS (code, name) values ('MUJ', 'Mui River Airport');
insert into AIRPORTS (code, name) values ('MYX', 'Menyamya Airport');
insert into AIRPORTS (code, name) values ('LCB', 'Pontes e Lacerda Airport');
insert into AIRPORTS (code, name) values ('LLE', 'Riverside Airport');
insert into AIRPORTS (code, name) values ('VND', 'Vangaindrano Airport');
insert into AIRPORTS (code, name) values ('CBQ', 'Margaret Ekpo International Airport');
insert into AIRPORTS (code, name) values ('KIK', 'Kirkuk Air Base');
insert into AIRPORTS (code, name) values ('GWN', 'Gnarowein Airport');
insert into AIRPORTS (code, name) values ('RAP', 'Rapid City Regional Airport');
insert into AIRPORTS (code, name) values ('NRA', 'Narrandera Airport');
insert into AIRPORTS (code, name) values ('MXA', 'Manila Municipal Airport');
insert into AIRPORTS (code, name) values ('ZOF', 'Ocean Falls Seaplane Base');
insert into AIRPORTS (code, name) values ('DTB', 'Silangit Airport');
insert into AIRPORTS (code, name) values ('ISO', 'Kinston Regional Jetport At Stallings Field');
insert into AIRPORTS (code, name) values ('CFG', 'Jaime Gonzalez Airport');
insert into AIRPORTS (code, name) values ('MPN', 'Mount Pleasant Airport');
insert into AIRPORTS (code, name) values ('IRU', 'Iranamadu Seaplane Base');
insert into AIRPORTS (code, name) values ('JIB', 'Djibouti-Ambouli Airport');
insert into AIRPORTS (code, name) values ('AOH', 'Lima Allen County Airport');
insert into AIRPORTS (code, name) values ('SJH', 'San Juan Del César Airport');
insert into AIRPORTS (code, name) values ('UMC', 'Umba Airport');
insert into AIRPORTS (code, name) values ('OYK', 'Oiapoque Airport');
insert into AIRPORTS (code, name) values ('QLR', 'Monte Real Air Base');
insert into AIRPORTS (code, name) values ('DRI', 'Beauregard Regional Airport');
insert into AIRPORTS (code, name) values ('JUJ', 'Gobernador Horacio Guzman International Airport');
insert into AIRPORTS (code, name) values ('JDR', 'Prefeito Octávio de Almeida Neves Airport');
insert into AIRPORTS (code, name) values ('FBR', 'Fort Bridger Airport');
insert into AIRPORTS (code, name) values ('EDD', 'Erldunda Airport');
insert into AIRPORTS (code, name) values ('BTW', 'Batu Licin Airport');
insert into AIRPORTS (code, name) values ('KSL', 'Kassala Airport');
insert into AIRPORTS (code, name) values ('CHR', 'Châteauroux-Déols "Marcel Dassault" Airport');
insert into AIRPORTS (code, name) values ('KOL', 'Koumala Airport');
insert into AIRPORTS (code, name) values ('BEC', 'Beech Factory Airport');
insert into AIRPORTS (code, name) values ('LRL', 'Niamtougou International Airport');
insert into AIRPORTS (code, name) values ('GSB', 'Seymour Johnson Air Force Base');
insert into AIRPORTS (code, name) values ('JSA', 'Jaisalmer Airport');
insert into AIRPORTS (code, name) values ('JSA', 'Jaisalmer Airport');
insert into AIRPORTS (code, name) values ('MLA', 'Malta International Airport');
insert into AIRPORTS (code, name) values ('APG', 'Phillips Army Air Field');
insert into AIRPORTS (code, name) values ('MKV', 'Mount Cavenagh Airport');
insert into AIRPORTS (code, name) values ('GZT', 'Gaziantep International Airport');
insert into AIRPORTS (code, name) values ('SMG', 'Santa Maria Airport');
insert into AIRPORTS (code, name) values ('MAC', 'Macon Downtown Airport');
insert into AIRPORTS (code, name) values ('BVM', 'Belmonte Airport');
insert into AIRPORTS (code, name) values ('DON', 'Dos Lagunas Airport');
insert into AIRPORTS (code, name) values ('KWT', 'Kwethluk Airport');
insert into AIRPORTS (code, name) values ('HUT', 'Hutchinson Municipal Airport');
insert into AIRPORTS (code, name) values ('QJE', 'Kitsissuarsuit Heliport');
insert into AIRPORTS (code, name) values ('CXY', 'Cat Cay Airport');
insert into AIRPORTS (code, name) values ('OTZ', 'Ralph Wien Memorial Airport');
insert into AIRPORTS (code, name) values ('CNU', 'Chanute Martin Johnson Airport');
insert into AIRPORTS (code, name) values ('SPF', 'Black Hills Airport-Clyde Ice Field');
insert into AIRPORTS (code, name) values ('CFO', 'Confresa Airport');
insert into AIRPORTS (code, name) values ('YWJ', 'Déline Airport');
insert into AIRPORTS (code, name) values ('YHZ', 'Halifax / Stanfield International Airport');
insert into AIRPORTS (code, name) values ('CBO', 'Awang Airport');
insert into AIRPORTS (code, name) values ('KHM', 'Kanti Airport');
insert into AIRPORTS (code, name) values ('ORX', 'Oriximiná Airport');
insert into AIRPORTS (code, name) values ('HTL', 'Roscommon County - Blodgett Memorial Airport');
insert into AIRPORTS (code, name) values ('VCA', 'Can Tho International Airport');
insert into AIRPORTS (code, name) values ('BST', 'Bost Airport');
insert into AIRPORTS (code, name) values ('NGU', 'Norfolk Naval Station (Chambers Field)');
insert into AIRPORTS (code, name) values ('CDF', 'Cortina Airport');
insert into AIRPORTS (code, name) values ('SJE', 'Jorge E. Gonzalez Torres Airport');
insert into AIRPORTS (code, name) values ('YTR', 'CFB Trenton');
insert into AIRPORTS (code, name) values ('GUL', 'Goulburn Airport');
insert into AIRPORTS (code, name) values ('MGC', 'Michigan City Municipal Airport');
insert into AIRPORTS (code, name) values ('VIT', 'Vitoria/Foronda Airport');
insert into AIRPORTS (code, name) values ('XPA', 'Pama Airport');
insert into AIRPORTS (code, name) values ('NQL', 'Niquelândia Airport');
insert into AIRPORTS (code, name) values ('OTJ', 'Otjiwarongo Airport');
insert into AIRPORTS (code, name) values ('PPV', 'Port Protection Seaplane Base');
insert into AIRPORTS (code, name) values ('LUD', 'Luderitz Airport');
insert into AIRPORTS (code, name) values ('AJY', 'Mano Dayak International Airport');
insert into AIRPORTS (code, name) values ('DUS', 'Düsseldorf Airport');
insert into AIRPORTS (code, name) values ('EMI', 'Emirau Airport');
insert into AIRPORTS (code, name) values ('MXT', 'Maintirano Airport');
insert into AIRPORTS (code, name) values ('XIL', 'Xilinhot Airport');
insert into AIRPORTS (code, name) values ('CPL', 'Chaparral Airport');
insert into AIRPORTS (code, name) values ('BJF', 'Båtsfjord Airport');
insert into AIRPORTS (code, name) values ('MOQ', 'Morondava Airport');
insert into AIRPORTS (code, name) values ('TNS', 'Tungsten (Cantung) Airport');
insert into AIRPORTS (code, name) values ('BST', 'Bost Airport');
insert into AIRPORTS (code, name) values ('YOG', 'Ogoki Post Airport');
insert into AIRPORTS (code, name) values ('0', 'Usina Mandu Airport');
insert into AIRPORTS (code, name) values ('ZTH', 'Zakynthos International Airport "Dionysios Solomos"');
insert into AIRPORTS (code, name) values ('UZU', 'Curuzu Cuatia Airport');
insert into AIRPORTS (code, name) values ('LNN', 'Willoughby Lost Nation Municipal Airport');
insert into AIRPORTS (code, name) values ('ENT', 'Eniwetok Airport');
insert into AIRPORTS (code, name) values ('NYE', 'Nyeri Airport');
insert into AIRPORTS (code, name) values ('XTL', 'Tadoule Lake Airport');
insert into AIRPORTS (code, name) values ('YGT', 'Igloolik Airport');
insert into AIRPORTS (code, name) values ('TBR', 'Statesboro Bulloch County Airport');
insert into AIRPORTS (code, name) values ('LDE', 'Tarbes-Lourdes-Pyrénées Airport');
insert into AIRPORTS (code, name) values ('ERC', 'Erzincan Airport');
insert into AIRPORTS (code, name) values ('BJC', 'Rocky Mountain Metropolitan Airport');
insert into AIRPORTS (code, name) values ('OKG', 'Okoyo Airport');
insert into AIRPORTS (code, name) values ('EIH', 'Einasleigh Airport');
insert into AIRPORTS (code, name) values ('YHI', 'Ulukhaktok Holman Airport');
insert into AIRPORTS (code, name) values ('FIE', 'Fair Isle Airport');
insert into AIRPORTS (code, name) values ('HHQ', 'Hua Hin Airport');
insert into AIRPORTS (code, name) values ('OVE', 'Oroville Municipal Airport');
insert into AIRPORTS (code, name) values ('PCT', 'Princeton Airport');
insert into AIRPORTS (code, name) values ('BVP', 'Bolovip Airstrip');
insert into AIRPORTS (code, name) values ('FUT', 'Pointe Vele Airport');
insert into AIRPORTS (code, name) values ('NLD', 'Quetzalcóatl International Airport');
insert into AIRPORTS (code, name) values ('SHJ', 'Sharjah International Airport');
insert into AIRPORTS (code, name) values ('BDH', 'Bandar Lengeh Airport');
insert into AIRPORTS (code, name) values ('DUR', 'King Shaka International Airport');
insert into AIRPORTS (code, name) values ('FAS', 'Fáskrúðsfjörður Airport');
insert into AIRPORTS (code, name) values ('CDS', 'Childress Municipal Airport');
insert into AIRPORTS (code, name) values ('AUG', 'Augusta State Airport');
insert into AIRPORTS (code, name) values ('LGM', 'Laiagam Airport');
insert into AIRPORTS (code, name) values ('LCG', 'A Coruña Airport');
insert into AIRPORTS (code, name) values ('LUH', 'Ludhiana Airport');
insert into AIRPORTS (code, name) values ('FET', 'Fremont Municipal Airport');
insert into AIRPORTS (code, name) values ('SAT', 'San Antonio International Airport');
insert into AIRPORTS (code, name) values ('EDM', 'La Roche-sur-Yon Airport');
insert into AIRPORTS (code, name) values ('RCL', 'Redcliffe Airport');
insert into AIRPORTS (code, name) values ('JCU', 'Ceuta Heliport');
insert into AIRPORTS (code, name) values ('SSX', 'Singita Safari Lodge Airport');
insert into AIRPORTS (code, name) values ('RNN', 'Bornholm Airport');
insert into AIRPORTS (code, name) values ('DEL', 'Indira Gandhi International Airport');
insert into AIRPORTS (code, name) values ('LCM', 'La Cumbre Airport');
insert into AIRPORTS (code, name) values ('ACA', 'General Juan N Alvarez International Airport');
insert into AIRPORTS (code, name) values ('NKC', 'Nouakchott–Oumtounsy International Airport');
insert into AIRPORTS (code, name) values ('PKU', 'Sultan Syarif Kasim Ii (Simpang Tiga) Airport');
insert into AIRPORTS (code, name) values ('WHK', 'Whakatane Airport');
insert into AIRPORTS (code, name) values ('DNQ', 'Deniliquin Airport');
insert into AIRPORTS (code, name) values ('JCR', 'Jacareacanga Airport');
insert into AIRPORTS (code, name) values ('ZAT', 'Zhaotong Airport');
insert into AIRPORTS (code, name) values ('ECO', 'El Encanto Airport');
insert into AIRPORTS (code, name) values ('DNG', 'Doongan Airport');
insert into AIRPORTS (code, name) values ('MGX', 'Moabi Airport');
insert into AIRPORTS (code, name) values ('SKY', 'Griffing Sandusky Airport');
insert into AIRPORTS (code, name) values ('GLO', 'Gloucestershire Airport');
insert into AIRPORTS (code, name) values ('YVO', 'Val-d''Or Airport');
insert into AIRPORTS (code, name) values ('DUT', 'Unalaska Airport');
insert into AIRPORTS (code, name) values ('ZQL', 'Donaueschingen-Villingen Airport');
insert into AIRPORTS (code, name) values ('YXT', 'Northwest Regional Airport Terrace-Kitimat');
insert into AIRPORTS (code, name) values ('PRM', 'Proma Heliport');
insert into AIRPORTS (code, name) values ('EDI', 'Edinburgh Airport');
insert into AIRPORTS (code, name) values ('OFK', 'Karl Stefan Memorial Airport');
insert into AIRPORTS (code, name) values ('SDD', 'Lubango Airport');
insert into AIRPORTS (code, name) values ('NZA', 'Nzagi Airport');
insert into AIRPORTS (code, name) values ('HUV', 'Hudiksvall Airport');
insert into AIRPORTS (code, name) values ('TOC', 'Toccoa Airport - R.G. Letourneau Field');
insert into AIRPORTS (code, name) values ('GWT', 'Westerland Sylt Airport');
insert into AIRPORTS (code, name) values ('TLU', 'Golfo de Morrosquillo Airport');
insert into AIRPORTS (code, name) values ('NAF', 'Banaina Airport');
insert into AIRPORTS (code, name) values ('BKN', 'Balkanabat Airport');
insert into AIRPORTS (code, name) values ('PYL', 'Perry Island Seaplane Base');
insert into AIRPORTS (code, name) values ('LTP', 'Lyndhurst Airport');
insert into AIRPORTS (code, name) values ('BQO', 'Bouna Airport');
insert into AIRPORTS (code, name) values ('SXP', 'Nunam Iqua Airport');
insert into AIRPORTS (code, name) values ('TJS', 'Tanjung Harapan Airport');
insert into AIRPORTS (code, name) values ('YBC', 'Baie Comeau Airport');
insert into AIRPORTS (code, name) values ('LEK', 'Tata Airport');
insert into AIRPORTS (code, name) values ('RSX', 'Rouses Point Seaplane Base');
insert into AIRPORTS (code, name) values ('LIB', 'Limbunya Airport');
insert into AIRPORTS (code, name) values ('TXM', 'Teminabuan Airport');
insert into AIRPORTS (code, name) values ('GUI', 'Guiria Airport');
insert into AIRPORTS (code, name) values ('GNN', 'Ghinnir Airport');
insert into AIRPORTS (code, name) values ('BVU', 'Beluga Airport');
insert into AIRPORTS (code, name) values ('BYK', 'Bouaké Airport');
insert into AIRPORTS (code, name) values ('MWK', 'Tarempa Airport');
insert into AIRPORTS (code, name) values ('HNC', 'Billy Mitchell Airport');
insert into AIRPORTS (code, name) values ('SKU', 'Skiros Airport');
insert into AIRPORTS (code, name) values ('CES', 'Cessnock Airport');
insert into AIRPORTS (code, name) values ('LLF', 'Lingling Airport');
insert into AIRPORTS (code, name) values ('VSA', 'Carlos Rovirosa Pérez International Airport');
insert into AIRPORTS (code, name) values ('JAC', 'Jackson Hole Airport');
insert into AIRPORTS (code, name) values ('ELU', 'Guemar Airport');
insert into AIRPORTS (code, name) values ('UNK', 'Unalakleet Airport');
insert into AIRPORTS (code, name) values ('YMS', 'Moises Benzaquen Rengifo Airport');
insert into AIRPORTS (code, name) values ('BZT', 'Eagle Air Park');
insert into AIRPORTS (code, name) values ('LAB', 'Lab Lab Airport');
insert into AIRPORTS (code, name) values ('SPH', 'Sopu Airport');
insert into AIRPORTS (code, name) values ('RBQ', 'Rurenabaque Airport');
insert into AIRPORTS (code, name) values ('YHF', 'Hearst René Fontaine Municipal Airport');
insert into AIRPORTS (code, name) values ('PRB', 'Paso Robles Municipal Airport');
insert into AIRPORTS (code, name) values ('HNL', 'Daniel K Inouye International Airport');
insert into AIRPORTS (code, name) values ('WEI', 'Weipa Airport');
insert into AIRPORTS (code, name) values ('YGB', 'Texada Gillies Bay Airport');
insert into AIRPORTS (code, name) values ('ZIN', 'Interlaken Air Base');
insert into AIRPORTS (code, name) values ('TNK', 'Tununak Airport');
insert into AIRPORTS (code, name) values ('SAX', 'Sambu Airport');
insert into AIRPORTS (code, name) values ('CRF', 'Carnot Airport');
insert into AIRPORTS (code, name) values ('ALF', 'Alta Airport');
insert into AIRPORTS (code, name) values ('MNI', 'John A. Osborne Airport');
insert into AIRPORTS (code, name) values ('DLA', 'Douala International Airport');
insert into AIRPORTS (code, name) values ('WYS', 'Yellowstone Airport');
insert into AIRPORTS (code, name) values ('MNF', 'Mana Island Airport');
insert into AIRPORTS (code, name) values ('CTL', 'Charleville Airport');
insert into AIRPORTS (code, name) values ('OBI', 'Óbidos Airport');
insert into AIRPORTS (code, name) values ('GNV', 'Gainesville Regional Airport');
insert into AIRPORTS (code, name) values ('AZS', 'Samaná El Catey International Airport');
insert into AIRPORTS (code, name) values ('XMS', 'Coronel E Carvajal Airport');
insert into AIRPORTS (code, name) values ('UIH', 'Phu Cat Airport');
insert into AIRPORTS (code, name) values ('RST', 'Rochester International Airport');
insert into AIRPORTS (code, name) values ('XPK', 'Pukatawagan Airport');
insert into AIRPORTS (code, name) values ('OPU', 'Balimo Airport');
insert into AIRPORTS (code, name) values ('SQX', 'São Miguel do Oeste Airport');
insert into AIRPORTS (code, name) values ('KGX', 'Grayling Airport');
insert into AIRPORTS (code, name) values ('0', 'Santa Paula Airport');
insert into AIRPORTS (code, name) values ('WIE', 'Wiesbaden Army Airfield');
insert into AIRPORTS (code, name) values ('SJZ', 'São Jorge Airport');
insert into AIRPORTS (code, name) values ('SAS', 'Salton Sea Airport');
insert into AIRPORTS (code, name) values ('NNY', 'Nanyang Jiangying Airport');
insert into AIRPORTS (code, name) values ('RFR', 'Rio Frio / Progreso Airport');
insert into AIRPORTS (code, name) values ('HEE', 'Thompson-Robbins Airport');
insert into AIRPORTS (code, name) values ('ONG', 'Mornington Island Airport');
insert into AIRPORTS (code, name) values ('PBP', 'Islita Airport');
insert into AIRPORTS (code, name) values ('MBT', 'Moises R. Espinosa Airport');
insert into AIRPORTS (code, name) values ('HNC', 'Billy Mitchell Airport');
insert into AIRPORTS (code, name) values ('OGO', 'Abengourou Airport');
insert into AIRPORTS (code, name) values ('IPI', 'San Luis Airport');
insert into AIRPORTS (code, name) values ('UAX', 'Uaxactun Airport');
insert into AIRPORTS (code, name) values ('TKL', 'Taku Lodge Seaplane Base');
insert into AIRPORTS (code, name) values ('MSO', 'Missoula International Airport');
insert into AIRPORTS (code, name) values ('PIB', 'Hattiesburg Laurel Regional Airport');
insert into AIRPORTS (code, name) values ('JGO', 'Qeqertarsuaq Heliport');
insert into AIRPORTS (code, name) values ('SFZ', 'North Central State Airport');
insert into AIRPORTS (code, name) values ('DLE', 'Dole-Tavaux Airport');
insert into AIRPORTS (code, name) values ('SNK', 'Winston Field');
insert into AIRPORTS (code, name) values ('HJJ', 'Zhijiang Airport');
insert into AIRPORTS (code, name) values ('TTI', 'Tetiaroa Airport');
insert into AIRPORTS (code, name) values ('CBU', 'Cottbus-Drewitz Airport');
insert into AIRPORTS (code, name) values ('CTY', 'Cross City Airport');
insert into AIRPORTS (code, name) values ('GKK', 'Kooddoo Airport');
insert into AIRPORTS (code, name) values ('OTM', 'Ottumwa Regional Airport');
insert into AIRPORTS (code, name) values ('SDJ', 'Sendai Airport');
insert into AIRPORTS (code, name) values ('YBG', 'CFB Bagotville');
insert into AIRPORTS (code, name) values ('LCM', 'La Cumbre Airport');
insert into AIRPORTS (code, name) values ('RUY', 'Copán Ruinas Airport');
insert into AIRPORTS (code, name) values ('MQC', 'Miquelon Airport');
insert into AIRPORTS (code, name) values ('YVZ', 'Deer Lake Airport');
insert into AIRPORTS (code, name) values ('VXO', 'Växjö Kronoberg Airport');
insert into AIRPORTS (code, name) values ('CCC', 'Jardines Del Rey Airport');
insert into AIRPORTS (code, name) values ('PWM', 'Portland International Jetport Airport');
insert into AIRPORTS (code, name) values ('EFW', 'Jefferson Municipal Airport');
insert into AIRPORTS (code, name) values ('BEM', 'Beni Mellal Airport');
insert into AIRPORTS (code, name) values ('TMJ', 'Termez Airport');
insert into AIRPORTS (code, name) values ('AYE', 'Ft Devens Moore Army Air Field');
insert into AIRPORTS (code, name) values ('GBJ', 'Les Bases Airport');
insert into AIRPORTS (code, name) values ('MGL', 'Mönchengladbach Airport');
insert into AIRPORTS (code, name) values ('HSM', 'Horsham Airport');
insert into AIRPORTS (code, name) values ('NKT', 'Şırnak Şerafettin Elçi Airport');
insert into AIRPORTS (code, name) values ('CIG', 'Craig Moffat Airport');
insert into AIRPORTS (code, name) values ('CAM', 'Camiri Airport');
insert into AIRPORTS (code, name) values ('CRZ', 'Turkmenabat Airport');
insert into AIRPORTS (code, name) values ('RUK', 'Rukum Chaurjahari Airport');
insert into AIRPORTS (code, name) values ('RDV', 'Red Devil Airport');
insert into AIRPORTS (code, name) values ('YML', 'Charlevoix Airport');
insert into AIRPORTS (code, name) values ('MXX', 'Mora Airport');
insert into AIRPORTS (code, name) values ('OCJ', 'Boscobel Aerodrome');
insert into AIRPORTS (code, name) values ('CRW', 'Yeager Airport');
insert into AIRPORTS (code, name) values ('YKF', 'Waterloo Airport');
insert into AIRPORTS (code, name) values ('PQQ', 'Port Macquarie Airport');
insert into AIRPORTS (code, name) values ('HRE', 'Robert Gabriel Mugabe International Airport');
insert into AIRPORTS (code, name) values ('SJZ', 'São Jorge Airport');
insert into AIRPORTS (code, name) values ('TWP', 'Torwood Airport');
insert into AIRPORTS (code, name) values ('MLW', 'Spriggs Payne Airport');
insert into AIRPORTS (code, name) values ('AOS', 'Amook Bay Seaplane Base');
insert into AIRPORTS (code, name) values ('MRM', 'Manari Airport');
insert into AIRPORTS (code, name) values ('REP', 'Siem Reap International Airport');
insert into AIRPORTS (code, name) values ('BID', 'Block Island State Airport');
insert into AIRPORTS (code, name) values ('YYA', 'Sanhe Airport');
insert into AIRPORTS (code, name) values ('IFP', 'Laughlin Bullhead International Airport');
insert into AIRPORTS (code, name) values ('MLB', 'Melbourne International Airport');
insert into AIRPORTS (code, name) values ('YQK', 'Kenora Airport');
insert into AIRPORTS (code, name) values ('BJQ', 'Bahja Airport');
insert into AIRPORTS (code, name) values ('SKC', 'Suki Airport');
insert into AIRPORTS (code, name) values ('MDD', 'Midland Airpark');
insert into AIRPORTS (code, name) values ('DYL', 'Doylestown Airport');
insert into AIRPORTS (code, name) values ('KGD', 'Khrabrovo Airport');
insert into AIRPORTS (code, name) values ('MXY', 'Mc Carthy Airport');
insert into AIRPORTS (code, name) values ('FAL', 'Falcon State Airport');
insert into AIRPORTS (code, name) values ('MMV', 'Mal Airport');
insert into AIRPORTS (code, name) values ('GGM', 'Kakamega Airport');
insert into AIRPORTS (code, name) values ('BVU', 'Beluga Airport');
insert into AIRPORTS (code, name) values ('PHA', 'Phan Rang Airport');
insert into AIRPORTS (code, name) values ('YTQ', 'Tasiujaq Airport');
insert into AIRPORTS (code, name) values ('MPM', 'Maputo Airport');
insert into AIRPORTS (code, name) values ('PZO', 'General Manuel Carlos Piar International Airport');
insert into AIRPORTS (code, name) values ('YCY', 'Clyde River Airport');
insert into AIRPORTS (code, name) values ('NZA', 'Nzagi Airport');
insert into AIRPORTS (code, name) values ('LRO', 'Sharpe AAF');
insert into AIRPORTS (code, name) values ('ZZU', 'Mzuzu Airport');
insert into AIRPORTS (code, name) values ('ATV', 'Ati Airport');
insert into AIRPORTS (code, name) values ('BVZ', 'Beverley Springs Airport');
insert into AIRPORTS (code, name) values ('ZKM', 'Sette Cama Airport');
insert into AIRPORTS (code, name) values ('ATG', 'Minhas Air Base');
insert into AIRPORTS (code, name) values ('THT', 'Tamchakett Airport');
insert into AIRPORTS (code, name) values ('EUX', 'F. D. Roosevelt Airport');
insert into AIRPORTS (code, name) values ('MZI', 'Mopti Airport');
insert into AIRPORTS (code, name) values ('WTP', 'Woitape Airport');
insert into AIRPORTS (code, name) values ('VIN', 'Vinnytsia/Gavyryshivka Airport');
insert into AIRPORTS (code, name) values ('IDP', 'Independence Municipal Airport');
insert into AIRPORTS (code, name) values ('RCK', 'H H Coffield Regional Airport');
insert into AIRPORTS (code, name) values ('GIF', 'Winter Haven Regional Airport - Gilbert Field');
insert into AIRPORTS (code, name) values ('KXE', 'P C Pelser Airport');
insert into AIRPORTS (code, name) values ('OCM', 'Boolgeeda');
insert into AIRPORTS (code, name) values ('RWI', 'Rocky Mount Wilson Regional Airport');
insert into AIRPORTS (code, name) values ('LOY', 'Loyengalani Airport');
insert into AIRPORTS (code, name) values ('RIV', 'March ARB Airport');
insert into AIRPORTS (code, name) values ('LED', 'Pulkovo Airport');
insert into AIRPORTS (code, name) values ('ELO', 'El Dorado Airport');
insert into AIRPORTS (code, name) values ('VAW', 'Vardø Airport, Svartnes');
insert into AIRPORTS (code, name) values ('LSV', 'Nellis Air Force Base');
insert into AIRPORTS (code, name) values ('POD', 'Podor Airport');
insert into AIRPORTS (code, name) values ('ICN', 'Incheon International Airport');
insert into AIRPORTS (code, name) values ('CZT', 'Dimmit County Airport');
insert into AIRPORTS (code, name) values ('KMK', 'Makabana Airport');
insert into AIRPORTS (code, name) values ('PSN', 'Palestine Municipal Airport');
insert into AIRPORTS (code, name) values ('HJR', 'Khajuraho Airport');
insert into AIRPORTS (code, name) values ('VAS', 'Sivas Nuri Demirağ Airport');
insert into AIRPORTS (code, name) values ('UKK', 'Ust-Kamennogorsk Airport');
insert into AIRPORTS (code, name) values ('OGD', 'Ogden Hinckley Airport');
insert into AIRPORTS (code, name) values ('0', 'Oeiras Airport');
insert into AIRPORTS (code, name) values ('AGU', 'Jesús Terán Paredo International Airport');
insert into AIRPORTS (code, name) values ('MIH', 'Mitchell Plateau Airport');
insert into AIRPORTS (code, name) values ('NOZ', 'Spichenkovo Airport');
insert into AIRPORTS (code, name) values ('HRY', 'Henbury Airport');
insert into AIRPORTS (code, name) values ('BIV', 'Bria Airport');
insert into AIRPORTS (code, name) values ('BDC', 'Barra do Corda Airport');
insert into AIRPORTS (code, name) values ('BZN', 'Gallatin Field');
insert into AIRPORTS (code, name) values ('VBY', 'Visby Airport');
insert into AIRPORTS (code, name) values ('WAD', 'Andriamena Airport');
insert into AIRPORTS (code, name) values ('KAR', 'Kamarang Airport');
insert into AIRPORTS (code, name) values ('OEA', 'O''Neal Airport');
insert into AIRPORTS (code, name) values ('BOK', 'Brookings Airport');
insert into AIRPORTS (code, name) values ('UBS', 'Columbus Lowndes County Airport');
insert into AIRPORTS (code, name) values ('MDN', 'Madison Municipal Airport');
insert into AIRPORTS (code, name) values ('FST', 'Fort Stockton Pecos County Airport');
insert into AIRPORTS (code, name) values ('BIG', 'Allen Army Airfield');
insert into AIRPORTS (code, name) values ('RXS', 'Roxas Airport');
insert into AIRPORTS (code, name) values ('FKL', 'Venango Regional Airport');
insert into AIRPORTS (code, name) values ('MJT', 'Mytilene International Airport');
insert into AIRPORTS (code, name) values ('HZP', 'Fort Mackay / Horizon Airport');
insert into AIRPORTS (code, name) values ('LOA', 'Lorraine Airport');
insert into AIRPORTS (code, name) values ('LWL', 'Wells Municipal Airport/Harriet Field');
insert into AIRPORTS (code, name) values ('KCC', 'Coffman Cove Seaplane Base');
insert into AIRPORTS (code, name) values ('VNA', 'Saravane Airport');
insert into AIRPORTS (code, name) values ('FAF', 'Felker Army Air Field');
insert into AIRPORTS (code, name) values ('BXB', 'Babo Airport');
insert into AIRPORTS (code, name) values ('LUP', 'Kalaupapa Airport');
insert into AIRPORTS (code, name) values ('AJL', 'Lengpui Airport');
insert into AIRPORTS (code, name) values ('STM', 'Maestro Wilson Fonseca Airport');
insert into AIRPORTS (code, name) values ('SER', 'Freeman Municipal Airport');
insert into AIRPORTS (code, name) values ('XLW', 'Lemwerder Airport');
insert into AIRPORTS (code, name) values ('GKA', 'Goroka Airport');
insert into AIRPORTS (code, name) values ('RGH', 'Balurghat Airport');
insert into AIRPORTS (code, name) values ('LNX', 'Smolensk North Airport');
insert into AIRPORTS (code, name) values ('LRH', 'La Rochelle-Île de Ré Airport');
insert into AIRPORTS (code, name) values ('SUQ', 'Sucua Airport');
insert into AIRPORTS (code, name) values ('ZEM', 'Eastmain River Airport');
insert into AIRPORTS (code, name) values ('UBP', 'Ubon Ratchathani Airport');
insert into AIRPORTS (code, name) values ('COJ', 'Coonabarabran Airport');
insert into AIRPORTS (code, name) values ('CZS', 'Cruzeiro do Sul Airport');
insert into AIRPORTS (code, name) values ('CNH', 'Claremont Municipal Airport');
insert into AIRPORTS (code, name) values ('AUZ', 'Aurora Municipal Airport');
insert into AIRPORTS (code, name) values ('BER', 'Berlin Brandenburg Airport (U.C.)');
insert into AIRPORTS (code, name) values ('YMA', 'Mayo Airport');
insert into AIRPORTS (code, name) values ('SRW', 'Mid-Carolina Regional Airport');
insert into AIRPORTS (code, name) values ('AHJ', 'Hongyuan Airport');
insert into AIRPORTS (code, name) values ('CHR', 'Châteauroux-Déols "Marcel Dassault" Airport');
insert into AIRPORTS (code, name) values ('JEG', 'Aasiaat Airport');
insert into AIRPORTS (code, name) values ('PHM', 'Böblingen Flugfeld');
insert into AIRPORTS (code, name) values ('CAD', 'Wexford County Airport');
insert into AIRPORTS (code, name) values ('CWS', 'Center Island Airport');
insert into AIRPORTS (code, name) values ('KOH', 'Koolatah Airport');
insert into AIRPORTS (code, name) values ('COI', 'Merritt Island Airport');
insert into AIRPORTS (code, name) values ('KSQ', 'Karshi Khanabad Airport');
insert into AIRPORTS (code, name) values ('QVR', 'Volta Redonda Airport');
insert into AIRPORTS (code, name) values ('MJJ', 'Moki Airport');
insert into AIRPORTS (code, name) values ('LLG', 'Chillagoe Airport');
insert into AIRPORTS (code, name) values ('COC', 'Comodoro Pierrestegui Airport');
insert into AIRPORTS (code, name) values ('INH', 'Inhambane Airport');
insert into AIRPORTS (code, name) values ('CKY', 'Conakry International Airport');
insert into AIRPORTS (code, name) values ('EGO', 'Belgorod International Airport');
insert into AIRPORTS (code, name) values ('OOM', 'Cooma Snowy Mountains Airport');
insert into AIRPORTS (code, name) values ('OGE', 'Ogeranang Airport');
insert into AIRPORTS (code, name) values ('EKI', 'Elkhart Municipal Airport');
insert into AIRPORTS (code, name) values ('KWN', 'Quinhagak Airport');
insert into AIRPORTS (code, name) values ('TKB', 'Tekadu Airport');
insert into AIRPORTS (code, name) values ('TON', 'Tonu Airport');
insert into AIRPORTS (code, name) values ('KSX', 'Yasuru Airport');
insert into AIRPORTS (code, name) values ('LUU', 'Laura Airport');
insert into AIRPORTS (code, name) values ('BQE', 'Bubaque Airport');
insert into AIRPORTS (code, name) values ('GTI', 'Flugplatz Güttin / Rügen');
insert into AIRPORTS (code, name) values ('RTS', 'Rottnest Island Airport');
insert into AIRPORTS (code, name) values ('CIV', 'Chomley Seaplane Base');
insert into AIRPORTS (code, name) values ('WGA', 'Wagga Wagga City Airport');
insert into AIRPORTS (code, name) values ('DUT', 'Unalaska Airport');
insert into AIRPORTS (code, name) values ('BCA', 'Gustavo Rizo Airport');
insert into AIRPORTS (code, name) values ('OEM', 'Vincent Fayks Airport');
insert into AIRPORTS (code, name) values ('HUB', 'Humbert River Airport');
insert into AIRPORTS (code, name) values ('DJM', 'Djambala Airport');
insert into AIRPORTS (code, name) values ('HOD', 'Hodeidah International Airport');
insert into AIRPORTS (code, name) values ('SHS', 'Shashi Airport');
insert into AIRPORTS (code, name) values ('TJI', 'Trujillo Airport');
insert into AIRPORTS (code, name) values ('KSI', 'Kissidougou Airport');
insert into AIRPORTS (code, name) values ('AML', 'Puerto Armuelles Airport');
insert into AIRPORTS (code, name) values ('ZUM', 'Churchill Falls Airport');
insert into AIRPORTS (code, name) values ('ESA', 'Esa''ala Airport');
insert into AIRPORTS (code, name) values ('PEK', 'Beijing Capital International Airport');
insert into AIRPORTS (code, name) values ('SSK', 'Sturt Creek Airport');
insert into AIRPORTS (code, name) values ('NDJ', 'N''Djamena International Airport');
insert into AIRPORTS (code, name) values ('EAS', 'San Sebastian Airport');
insert into AIRPORTS (code, name) values ('KKX', 'Kikai Airport');
insert into AIRPORTS (code, name) values ('VLI', 'Bauerfield International Airport');
insert into AIRPORTS (code, name) values ('MIH', 'Mitchell Plateau Airport');
insert into AIRPORTS (code, name) values ('SLA', 'Martin Miguel De Guemes International Airport');
insert into AIRPORTS (code, name) values ('CKL', 'Chkalovskiy Air Base');
insert into AIRPORTS (code, name) values ('DIK', 'Dickinson Theodore Roosevelt Regional Airport');
insert into AIRPORTS (code, name) values ('YSD', 'Suffield Heliport');
insert into AIRPORTS (code, name) values ('QGC', 'Lençóis Paulista Airport');
insert into AIRPORTS (code, name) values ('DRK', 'Drake Bay Airport');
insert into AIRPORTS (code, name) values ('TBO', 'Tabora Airport');
insert into AIRPORTS (code, name) values ('GLE', 'Gainesville Municipal Airport');
insert into AIRPORTS (code, name) values ('MBT', 'Moises R. Espinosa Airport');
insert into AIRPORTS (code, name) values ('KTC', 'Katiola Airport');
insert into AIRPORTS (code, name) values ('BBT', 'Berbérati Airport');
insert into AIRPORTS (code, name) values ('FPO', 'Grand Bahama International Airport');
insert into AIRPORTS (code, name) values ('OUM', 'Oum Hadjer Airport');
insert into AIRPORTS (code, name) values ('FOK', 'Francis S Gabreski Airport');
insert into AIRPORTS (code, name) values ('MPK', 'Mokpo Airport');
insert into AIRPORTS (code, name) values ('PWY', 'Ralph Wenz Field');
insert into AIRPORTS (code, name) values ('FUO', 'Foshan Shadi Airport');
insert into AIRPORTS (code, name) values ('FUK', 'Fukuoka Airport');
insert into AIRPORTS (code, name) values ('JLS', 'Jales Airport');
insert into AIRPORTS (code, name) values ('DLS', 'Columbia Gorge Regional the Dalles Municipal Airport');
insert into AIRPORTS (code, name) values ('HSB', 'Harrisburg-Raleigh Airport');
insert into AIRPORTS (code, name) values ('LDX', 'Saint-Laurent-du-Maroni Airport');
insert into AIRPORTS (code, name) values ('SHI', 'Shimojishima Airport');
insert into AIRPORTS (code, name) values ('ULH', 'Majeed Bin Abdulaziz Airport');
insert into AIRPORTS (code, name) values ('LXN', 'Jim Kelly Field');
insert into AIRPORTS (code, name) values ('LHW', 'Lanzhou Zhongchuan Airport');
insert into AIRPORTS (code, name) values ('OKI', 'Oki Airport');
insert into AIRPORTS (code, name) values ('IAD', 'Washington Dulles International Airport');
insert into AIRPORTS (code, name) values ('WOS', 'Wonsan Kalma International Airport');
insert into AIRPORTS (code, name) values ('KNU', 'Kanpur Airport');
insert into AIRPORTS (code, name) values ('LHP', 'Lehu Airport');
insert into AIRPORTS (code, name) values ('DGR', 'Dargaville Aerodrome');
insert into AIRPORTS (code, name) values ('LAX', 'Los Angeles International Airport');
insert into AIRPORTS (code, name) values ('DTW', 'Detroit Metropolitan Wayne County Airport');
insert into AIRPORTS (code, name) values ('ZPB', 'Sachigo Lake Airport');
insert into AIRPORTS (code, name) values ('AUM', 'Austin Municipal Airport');
insert into AIRPORTS (code, name) values ('MEF', 'Melfi Airport');
insert into AIRPORTS (code, name) values ('PVO', 'Reales Tamarindos Airport');
insert into AIRPORTS (code, name) values ('MJG', 'Mayajigua Airport');
insert into AIRPORTS (code, name) values ('ILN', 'Wilmington Airpark');
insert into AIRPORTS (code, name) values ('TSG', 'Tanacross Airport');
insert into AIRPORTS (code, name) values ('PDT', 'Eastern Oregon Regional At Pendleton Airport');
insert into AIRPORTS (code, name) values ('NNU', 'Nanuque Airport');
insert into AIRPORTS (code, name) values ('YPR', 'Prince Rupert Airport');
insert into AIRPORTS (code, name) values ('CUU', 'General Roberto Fierro Villalobos International Airport');
insert into AIRPORTS (code, name) values ('COT', 'Cotulla-La Salle County Airport');
insert into AIRPORTS (code, name) values ('0', 'Campina Verde Airport');
insert into AIRPORTS (code, name) values ('PPN', 'Guillermo León Valencia Airport');
insert into AIRPORTS (code, name) values ('XBE', 'Bearskin Lake Airport');
insert into AIRPORTS (code, name) values ('POI', 'Capitan Nicolas Rojas Airport');
insert into AIRPORTS (code, name) values ('AXM', 'El Eden Airport');
insert into AIRPORTS (code, name) values ('ZEL', 'Bella Bella (Campbell Island) Airport');
insert into AIRPORTS (code, name) values ('LTV', 'Lotus Vale Airport');
insert into AIRPORTS (code, name) values ('AYT', 'Antalya International Airport');
insert into AIRPORTS (code, name) values ('NAQ', 'Qaanaaq Airport');
insert into AIRPORTS (code, name) values ('IRM', 'Igrim Airport');
insert into AIRPORTS (code, name) values ('BKO', 'Modibo Keita International Airport');
insert into AIRPORTS (code, name) values ('KXF', 'Koro Island Airport');
insert into AIRPORTS (code, name) values ('SXW', 'Sauren Airport');
insert into AIRPORTS (code, name) values ('TPR', 'Tom Price Airport');
insert into AIRPORTS (code, name) values ('DXR', 'Danbury Municipal Airport');
insert into AIRPORTS (code, name) values ('KYI', 'Yalata Mission Airport');
insert into AIRPORTS (code, name) values ('SIP', 'Simferopol International Airport');
insert into AIRPORTS (code, name) values ('HPR', 'Pretoria Central Heliport');
insert into AIRPORTS (code, name) values ('MEY', 'Meghauli Airport');
insert into AIRPORTS (code, name) values ('KKB', 'Kitoi Bay Seaplane Base');
insert into AIRPORTS (code, name) values ('ISU', 'Sulaymaniyah International Airport');
insert into AIRPORTS (code, name) values ('LTA', 'Tzaneen Airport');
insert into AIRPORTS (code, name) values ('RMU', 'Región de Murcia International Airport');
insert into AIRPORTS (code, name) values ('ENI', 'El Nido Airport');
insert into AIRPORTS (code, name) values ('TEN', 'Tongren Fenghuang Airport');
insert into AIRPORTS (code, name) values ('MSA', 'Muskrat Dam Airport');
insert into AIRPORTS (code, name) values ('PPB', 'Presidente Prudente Airport');
insert into AIRPORTS (code, name) values ('BUO', 'Burao Airport');
insert into AIRPORTS (code, name) values ('ERZ', 'Erzurum International Airport');
insert into AIRPORTS (code, name) values ('ORC', 'Orocue Airport');
insert into AIRPORTS (code, name) values ('SQD', 'Shangrao Sanqingshan Airport');
insert into AIRPORTS (code, name) values ('WGA', 'Wagga Wagga City Airport');
insert into AIRPORTS (code, name) values ('ULG', 'Ölgii Airport');
insert into AIRPORTS (code, name) values ('ULK', 'Lensk Airport');
insert into AIRPORTS (code, name) values ('UCC', 'Yucca Airstrip');
insert into AIRPORTS (code, name) values ('TMF', 'Thimarafushi Airport');
insert into AIRPORTS (code, name) values ('SGF', 'Springfield Branson National Airport');
insert into AIRPORTS (code, name) values ('OUG', 'Ouahigouya Airport');
insert into AIRPORTS (code, name) values ('BFI', 'Boeing Field King County International Airport');
insert into AIRPORTS (code, name) values ('HLC', 'Hill City Municipal Airport');
insert into AIRPORTS (code, name) values ('FNJ', 'Pyongyang Sunan International Airport');
insert into AIRPORTS (code, name) values ('UTN', 'Pierre Van Ryneveld Airport');
insert into AIRPORTS (code, name) values ('NMC', 'Normans Cay Airport');
insert into AIRPORTS (code, name) values ('TTA', 'Tan Tan Airport');
insert into AIRPORTS (code, name) values ('LRF', 'Little Rock Air Force Base');
insert into AIRPORTS (code, name) values ('CYC', 'Caye Chapel Airport');
insert into AIRPORTS (code, name) values ('LYB', 'Edward Bodden Airfield');
insert into AIRPORTS (code, name) values ('SBI', 'Sambailo Airport');
insert into AIRPORTS (code, name) values ('IMN', 'Imane Airport');
insert into AIRPORTS (code, name) values ('PLF', 'Pala Airport');
insert into AIRPORTS (code, name) values ('KBZ', 'Kaikoura Airport');
insert into AIRPORTS (code, name) values ('PTW', 'Heritage Field');
insert into AIRPORTS (code, name) values ('HFN', 'Hornafjörður Airport');
insert into AIRPORTS (code, name) values ('QGF', 'Montenegro Airport');
insert into AIRPORTS (code, name) values ('TYT', 'Treinta y Tres Airport');
insert into AIRPORTS (code, name) values ('YQM', 'Greater Moncton International Airport');
insert into AIRPORTS (code, name) values ('MBH', 'Maryborough Airport');
insert into AIRPORTS (code, name) values ('PFB', 'Lauro Kurtz Airport');
insert into AIRPORTS (code, name) values ('PUN', 'Punia Airport');
insert into AIRPORTS (code, name) values ('IAL', 'Ialibu Airport');
insert into AIRPORTS (code, name) values ('XME', 'Maubeuge-Élesmes Airport');
insert into AIRPORTS (code, name) values ('PVK', 'Aktion National Airport');
insert into AIRPORTS (code, name) values ('ANR', 'Antwerp International Airport (Deurne)');
insert into AIRPORTS (code, name) values ('HEH', 'Heho Airport');
insert into AIRPORTS (code, name) values ('CIO', 'Teniente Col Carmelo Peralta Airport');
insert into AIRPORTS (code, name) values ('SFR', 'San Fernando Airport');
insert into AIRPORTS (code, name) values ('RJA', 'Rajahmundry Airport');
insert into AIRPORTS (code, name) values ('INM', 'Innamincka Airport');
insert into AIRPORTS (code, name) values ('CZE', 'José Leonardo Chirinos Airport');
insert into AIRPORTS (code, name) values ('PGD', 'Charlotte County Airport');
insert into AIRPORTS (code, name) values ('JRS', 'Jerusalem Airport');
insert into AIRPORTS (code, name) values ('HRM', 'Hassi R''Mel Airport');
insert into AIRPORTS (code, name) values ('JDR', 'Prefeito Octávio de Almeida Neves Airport');
insert into AIRPORTS (code, name) values ('0', 'Patrocínio Airport');
insert into AIRPORTS (code, name) values ('CTY', 'Cross City Airport');
insert into AIRPORTS (code, name) values ('HSB', 'Harrisburg-Raleigh Airport');
insert into AIRPORTS (code, name) values ('PBD', 'Porbandar Airport');
insert into AIRPORTS (code, name) values ('PLW', 'Mutiara Airport');
insert into AIRPORTS (code, name) values ('SXB', 'Strasbourg Airport');
insert into AIRPORTS (code, name) values ('MME', 'Durham Tees Valley Airport');
insert into AIRPORTS (code, name) values ('BZB', 'Bazaruto Island Airport');
insert into AIRPORTS (code, name) values ('YVP', 'Kuujjuaq Airport');
insert into AIRPORTS (code, name) values ('MUG', 'Mulege Airport');
insert into AIRPORTS (code, name) values ('BBV', 'Nero-Mer Airport');
insert into AIRPORTS (code, name) values ('HUU', 'Alferez Fap David Figueroa Fernandini Airport');
insert into AIRPORTS (code, name) values ('MBQ', 'Mbarara Airport');
insert into AIRPORTS (code, name) values ('VLA', 'Vandalia Municipal Airport');
insert into AIRPORTS (code, name) values ('HRY', 'Henbury Airport');
insert into AIRPORTS (code, name) values ('EML', 'Emmen Air Base');
insert into AIRPORTS (code, name) values ('SRL', 'Palo Verde Airport');
insert into AIRPORTS (code, name) values ('YIB', 'Atikokan Municipal Airport');
insert into AIRPORTS (code, name) values ('NUG', 'Nuguria Airstrip');
insert into AIRPORTS (code, name) values ('LNX', 'Smolensk North Airport');
insert into AIRPORTS (code, name) values ('MHN', 'Hooker County Airport');
insert into AIRPORTS (code, name) values ('RME', 'Griffiss International Airport');
insert into AIRPORTS (code, name) values ('PBX', 'Fazenda Piraguassu Airport');
insert into AIRPORTS (code, name) values ('JJD', 'Comandante Ariston Pessoa Airport');
insert into AIRPORTS (code, name) values ('CCC', 'Jardines Del Rey Airport');
insert into AIRPORTS (code, name) values ('KYD', 'Lanyu Airport');
insert into AIRPORTS (code, name) values ('FLV', 'Sherman Army Air Field');
insert into AIRPORTS (code, name) values ('ABH', 'Alpha Airport');
insert into AIRPORTS (code, name) values ('ATQ', 'Sri Guru Ram Dass Jee International Airport');
insert into AIRPORTS (code, name) values ('TOQ', 'Barriles Airport');
insert into AIRPORTS (code, name) values ('RCE', 'Roche Harbor Airport');
insert into AIRPORTS (code, name) values ('CRL', 'Brussels South Charleroi Airport');
insert into AIRPORTS (code, name) values ('YIC', 'Yichun Mingyueshan Airport');
insert into AIRPORTS (code, name) values ('IXQ', 'Kamalpur Airport');
insert into AIRPORTS (code, name) values ('YEU', 'Eureka Airport');
insert into AIRPORTS (code, name) values ('COX', 'Congo Town Airport');
insert into AIRPORTS (code, name) values ('QJE', 'Kitsissuarsuit Heliport');
insert into AIRPORTS (code, name) values ('LTK', 'Bassel Al-Assad International Airport');
insert into AIRPORTS (code, name) values ('LLL', 'Lissadell Airport');
insert into AIRPORTS (code, name) values ('GAZ', 'Guasopa Airport');
insert into AIRPORTS (code, name) values ('EDQ', 'Erandique Airport');
insert into AIRPORTS (code, name) values ('REH', 'Rehoboth Airport');
insert into AIRPORTS (code, name) values ('DOA', 'Doany Airport');
insert into AIRPORTS (code, name) values ('NMS', 'Namsang Airport');
insert into AIRPORTS (code, name) values ('YMU', 'Mansons Landing Seaplane Base');
insert into AIRPORTS (code, name) values ('ELG', 'El Golea Airport');
insert into AIRPORTS (code, name) values ('SBB', 'Santa Bárbara de Barinas Airport');
insert into AIRPORTS (code, name) values ('YCN', 'Cochrane Airport');
insert into AIRPORTS (code, name) values ('BZD', 'Balranald Airport');
insert into AIRPORTS (code, name) values ('ZIH', 'Ixtapa Zihuatanejo International Airport');
insert into AIRPORTS (code, name) values ('WHP', 'Whiteman Airport');
insert into AIRPORTS (code, name) values ('CJM', 'Chumphon Airport');
insert into AIRPORTS (code, name) values ('YEQ', 'Yenkis(Yankisa) Airport');
insert into AIRPORTS (code, name) values ('EDE', 'Northeastern Regional Airport');
insert into AIRPORTS (code, name) values ('NKG', 'Nanjing Lukou Airport');
insert into AIRPORTS (code, name) values ('QQT', 'Qeqertaq Heliport');
insert into AIRPORTS (code, name) values ('ZWA', 'Andapa Airport');
insert into AIRPORTS (code, name) values ('GDP', 'Guadalupe Airport');
insert into AIRPORTS (code, name) values ('DDN', 'Delta Downs Airport');
insert into AIRPORTS (code, name) values ('OLR', 'Salerno Landing Zone Airport');
insert into AIRPORTS (code, name) values ('DSC', 'Dschang Airport');
insert into AIRPORTS (code, name) values ('UMT', 'Umiat Airport');
insert into AIRPORTS (code, name) values ('MGQ', 'Aden Adde International Airport');
insert into AIRPORTS (code, name) values ('PPW', 'Papa Westray Airport');
insert into AIRPORTS (code, name) values ('AXX', 'Angel Fire Airport');
insert into AIRPORTS (code, name) values ('TIR', 'Tirupati Airport');
insert into AIRPORTS (code, name) values ('GSC', 'Gascoyne Junction Airport');
insert into AIRPORTS (code, name) values ('MSR', 'Muş Airport');
insert into AIRPORTS (code, name) values ('YPQ', 'Peterborough Airport');
insert into AIRPORTS (code, name) values ('VTE', 'Wattay International Airport');
insert into AIRPORTS (code, name) values ('KKM', 'Sa Pran Nak Airport');
insert into AIRPORTS (code, name) values ('TMQ', 'Tambao Airport');
insert into AIRPORTS (code, name) values ('MXI', 'Mati National Airport');
insert into AIRPORTS (code, name) values ('RVA', 'Farafangana Airport');
insert into AIRPORTS (code, name) values ('JIC', 'Jinchuan Airport');
insert into AIRPORTS (code, name) values ('OLI', 'Rif Airport');
insert into AIRPORTS (code, name) values ('TWY', 'Tawa Airport');
insert into AIRPORTS (code, name) values ('GVW', 'Richards-Gebaur Air Force Base');
insert into AIRPORTS (code, name) values ('WSY', 'Whitsunday Island Airport');
insert into AIRPORTS (code, name) values ('YKH', 'Yingkou Lanqi Airport');
insert into AIRPORTS (code, name) values ('TAS', 'Tashkent International Airport');
insert into AIRPORTS (code, name) values ('MLN', 'Melilla Airport');
insert into AIRPORTS (code, name) values ('ONJ', 'Odate Noshiro Airport');
insert into AIRPORTS (code, name) values ('PDB', 'Pedro Bay Airport');
insert into AIRPORTS (code, name) values ('RPV', 'Roper Valley Airport');
insert into AIRPORTS (code, name) values ('BRT', 'Bathurst Island Airport');
insert into AIRPORTS (code, name) values ('BLE', 'Borlange Airport');
insert into AIRPORTS (code, name) values ('HTA', 'Chita-Kadala Airport');
insert into AIRPORTS (code, name) values ('ORW', 'Ormara Airport');
insert into AIRPORTS (code, name) values ('SJB', 'San Joaquín Airport');
insert into AIRPORTS (code, name) values ('LCP', 'Loncopue Airport');
insert into AIRPORTS (code, name) values ('CJH', 'Chilko Lake (Tsylos Park Lodge) Airport');
insert into AIRPORTS (code, name) values ('UKN', 'Waukon Municipal Airport');
insert into AIRPORTS (code, name) values ('YEQ', 'Yenkis(Yankisa) Airport');
insert into AIRPORTS (code, name) values ('TLS', 'Toulouse-Blagnac Airport');
insert into AIRPORTS (code, name) values ('CDV', 'Merle K (Mudhole) Smith Airport');
insert into AIRPORTS (code, name) values ('AFZ', 'Sabzevar National Airport');
insert into AIRPORTS (code, name) values ('SGZ', 'Songkhla Airport');
insert into AIRPORTS (code, name) values ('PVW', 'Hale County Airport');
insert into AIRPORTS (code, name) values ('BOB', 'Bora Bora Airport');
insert into AIRPORTS (code, name) values ('UOS', 'Franklin County Airport');
insert into AIRPORTS (code, name) values ('LYH', 'Lynchburg Regional Preston Glenn Field');
insert into AIRPORTS (code, name) values ('HKG', 'Hong Kong International Airport Kai Tak');
insert into AIRPORTS (code, name) values ('TRJ', 'Tarakbits Airport');
insert into AIRPORTS (code, name) values ('BQV', 'Bartlett Cove Seaplane Base');
insert into AIRPORTS (code, name) values ('BLM', 'Monmouth Executive Airport');
insert into AIRPORTS (code, name) values ('PSJ', 'Kasiguncu Airport');
insert into AIRPORTS (code, name) values ('WSA', 'Wasua Airport');
insert into AIRPORTS (code, name) values ('SEQ', 'Sungai Pakning Bengkalis Airport');
insert into AIRPORTS (code, name) values ('DLS', 'Columbia Gorge Regional the Dalles Municipal Airport');
insert into AIRPORTS (code, name) values ('SSO', 'São Lourenço Airport');
insert into AIRPORTS (code, name) values ('KBB', 'Kirkimbie Station Airport');
insert into AIRPORTS (code, name) values ('IRI', 'Iringa Airport');
insert into AIRPORTS (code, name) values ('LUJ', 'Lusikisiki Airport');
insert into AIRPORTS (code, name) values ('MSW', 'Massawa International Airport');
insert into AIRPORTS (code, name) values ('TYA', 'Klokovo Airfield');
insert into AIRPORTS (code, name) values ('QRR', 'Warren Airport');
insert into AIRPORTS (code, name) values ('PSO', 'Antonio Narino Airport');
insert into AIRPORTS (code, name) values ('PGB', 'Pangoa Airport');
insert into AIRPORTS (code, name) values ('HYR', 'Sawyer County Airport');
insert into AIRPORTS (code, name) values ('MYE', 'Miyakejima Airport');
insert into AIRPORTS (code, name) values ('PKV', 'Pskov Airport');
insert into AIRPORTS (code, name) values ('CIP', 'Chipata Airport');
insert into AIRPORTS (code, name) values ('RKA', 'Aratika Nord Airport');
insert into AIRPORTS (code, name) values ('BXU', 'Bancasi Airport');
insert into AIRPORTS (code, name) values ('ONQ', 'Zonguldak Airport');
insert into AIRPORTS (code, name) values ('YNM', 'Matagami Airport');
insert into AIRPORTS (code, name) values ('KYK', 'Karluk Airport');
insert into AIRPORTS (code, name) values ('SNU', 'Abel Santamaria Airport');
insert into AIRPORTS (code, name) values ('VAA', 'Vaasa Airport');
insert into AIRPORTS (code, name) values ('LAX', 'Los Angeles International Airport');
insert into AIRPORTS (code, name) values ('ATI', 'Artigas International Airport');
insert into AIRPORTS (code, name) values ('SOH', 'Solita Airport');
insert into AIRPORTS (code, name) values ('TOU', 'Touho Airport');
insert into AIRPORTS (code, name) values ('LGP', 'Legazpi City International Airport');
insert into AIRPORTS (code, name) values ('WET', 'Wagethe Airport');
insert into AIRPORTS (code, name) values ('FAJ', 'Diego Jimenez Torres Airport');
insert into AIRPORTS (code, name) values ('MRX', 'Mahshahr Airport');
insert into AIRPORTS (code, name) values ('NKW', 'Diego Garcia Naval Support Facility');
insert into AIRPORTS (code, name) values ('YYB', 'North Bay Jack Garland Airport');
insert into AIRPORTS (code, name) values ('SFS', 'Subic Bay International Airport');
insert into AIRPORTS (code, name) values ('MVQ', 'Mogilev Airport');
insert into AIRPORTS (code, name) values ('XBG', 'Bogande Airport');
insert into AIRPORTS (code, name) values ('EDB', 'El Debba Airport');
insert into AIRPORTS (code, name) values ('PHK', 'Palm Beach County Glades Airport');
insert into AIRPORTS (code, name) values ('WSZ', 'Westport Airport');
insert into AIRPORTS (code, name) values ('MPP', 'Mulatupo Airport');
insert into AIRPORTS (code, name) values ('TAV', 'Tau Airport');
insert into AIRPORTS (code, name) values ('MCD', 'Mackinac Island Airport');
insert into AIRPORTS (code, name) values ('GGD', 'Gregory Downs Airport');
insert into AIRPORTS (code, name) values ('LPO', 'La Porte Municipal Airport');
insert into AIRPORTS (code, name) values ('AMI', 'Selaparang Airport');
insert into AIRPORTS (code, name) values ('BDS', 'Brindisi – Salento Airport');
insert into AIRPORTS (code, name) values ('TGA', 'Tengah Air Base');
insert into AIRPORTS (code, name) values ('ART', 'Watertown International Airport');
insert into AIRPORTS (code, name) values ('YNE', 'Norway House Airport');
insert into AIRPORTS (code, name) values ('PTH', 'Port Heiden Airport');
insert into AIRPORTS (code, name) values ('THZ', 'Tahoua Airport');
insert into AIRPORTS (code, name) values ('SPQ', 'Catalina Air-Sea Terminal Heliport');
insert into AIRPORTS (code, name) values ('NRK', 'Norrköping Airport');
insert into AIRPORTS (code, name) values ('OOR', 'Mooraberree Airport');
insert into AIRPORTS (code, name) values ('WPR', 'Capitan Fuentes Martinez Airport Airport');
insert into AIRPORTS (code, name) values ('THP', 'Hot Springs County Airport');
insert into AIRPORTS (code, name) values ('DDP', 'Dorado Beach Airport');
insert into AIRPORTS (code, name) values ('RDD', 'Redding Municipal Airport');
insert into AIRPORTS (code, name) values ('0', 'Fazenda Palmital Airport');
insert into AIRPORTS (code, name) values ('GTR', 'Golden Triangle Regional Airport');
insert into AIRPORTS (code, name) values ('ASX', 'John F Kennedy Memorial Airport');
insert into AIRPORTS (code, name) values ('KJK', 'Wevelgem Airport');
insert into AIRPORTS (code, name) values ('YAH', 'La Grande-4 Airport');
insert into AIRPORTS (code, name) values ('VRK', 'Varkaus Airport');
insert into AIRPORTS (code, name) values ('TRD', 'Trondheim Airport Værnes');
insert into AIRPORTS (code, name) values ('KRJ', 'Karawari Airstrip');
insert into AIRPORTS (code, name) values ('VKS', 'Vicksburg Municipal Airport');
insert into AIRPORTS (code, name) values ('ZKE', 'Kashechewan Airport');
insert into AIRPORTS (code, name) values ('BCI', 'Barcaldine Airport');
insert into AIRPORTS (code, name) values ('BWU', 'Sydney Bankstown Airport');
insert into AIRPORTS (code, name) values ('TOR', 'Torrington Municipal Airport');
insert into AIRPORTS (code, name) values ('PRM', 'Proma Heliport');
insert into AIRPORTS (code, name) values ('YMD', 'Mould Bay Airport');
insert into AIRPORTS (code, name) values ('IDI', 'Indiana County/Jimmy Stewart Fld/ Airport');
insert into AIRPORTS (code, name) values ('YNL', 'Points North Landing Airport');
insert into AIRPORTS (code, name) values ('KFG', 'Kalkgurung Airport');
insert into AIRPORTS (code, name) values ('LSY', 'Lismore Airport');
insert into AIRPORTS (code, name) values ('CCY', 'Northeast Iowa Regional Airport');
insert into AIRPORTS (code, name) values ('SXN', 'Sua Pan Airport');
insert into AIRPORTS (code, name) values ('TJK', 'Tokat Airport');
insert into AIRPORTS (code, name) values ('EAL', 'Elenak Airport');
insert into AIRPORTS (code, name) values ('LYO', 'Lyons-Rice County Municipal Airport');
insert into AIRPORTS (code, name) values ('LXN', 'Jim Kelly Field');
insert into AIRPORTS (code, name) values ('YUS', 'Yushu Batang Airport');
insert into AIRPORTS (code, name) values ('MIZ', 'Mainoru Airstrip');
insert into AIRPORTS (code, name) values ('AXJ', 'Amakusa Airport');
insert into AIRPORTS (code, name) values ('NCI', 'Necocli Airport');
insert into AIRPORTS (code, name) values ('MUG', 'Mulege Airport');
insert into AIRPORTS (code, name) values ('TEX', 'Telluride Regional Airport');
insert into AIRPORTS (code, name) values ('RHL', 'Roy Hill Station Airport');
insert into AIRPORTS (code, name) values ('MZY', 'Mossel Bay Airport');
insert into AIRPORTS (code, name) values ('SVA', 'Savoonga Airport');
insert into AIRPORTS (code, name) values ('USI', 'Mabaruma Airport');
insert into AIRPORTS (code, name) values ('ECA', 'Iosco County Airport');
insert into AIRPORTS (code, name) values ('AHN', 'Athens Ben Epps Airport');
insert into AIRPORTS (code, name) values ('ABW', 'Abau Airport');
insert into AIRPORTS (code, name) values ('BMT', 'Beaumont Municipal Airport');
insert into AIRPORTS (code, name) values ('ZWL', 'Wollaston Lake Airport');
insert into AIRPORTS (code, name) values ('DES', 'Desroches Airport');
insert into AIRPORTS (code, name) values ('ESU', 'Mogador Airport');
insert into AIRPORTS (code, name) values ('WRY', 'Westray Airport');
insert into AIRPORTS (code, name) values ('CST', 'Castaway Island Seaplane Base');
insert into AIRPORTS (code, name) values ('BDS', 'Brindisi – Salento Airport');
insert into AIRPORTS (code, name) values ('DNK', 'Dnipropetrovsk International Airport');
insert into AIRPORTS (code, name) values ('OGD', 'Ogden Hinckley Airport');
insert into AIRPORTS (code, name) values ('MHD', 'Mashhad International Airport');
insert into AIRPORTS (code, name) values ('TJG', 'Warukin Airport');
insert into AIRPORTS (code, name) values ('WWD', 'Cape May County Airport');
insert into AIRPORTS (code, name) values ('MWJ', 'Matthews Ridge Airport');
insert into AIRPORTS (code, name) values ('APV', 'Apple Valley Airport');
insert into AIRPORTS (code, name) values ('IST', 'Istanbul Airport');
insert into AIRPORTS (code, name) values ('PPK', 'Petropavlosk South Airport');
insert into AIRPORTS (code, name) values ('LPQ', 'Luang Phabang International Airport');
insert into AIRPORTS (code, name) values ('RCA', 'Ellsworth Air Force Base');
insert into AIRPORTS (code, name) values ('OCW', 'Warren Field');
insert into AIRPORTS (code, name) values ('PLD', 'Playa Samara/Carrillo Airport');
insert into AIRPORTS (code, name) values ('BXV', 'Breiðdalsvík Airport');
insert into AIRPORTS (code, name) values ('KMC', 'King Khaled Military City Airport');
insert into AIRPORTS (code, name) values ('KAP', 'Kapanga Airport');
insert into AIRPORTS (code, name) values ('PNU', 'Panguitch Municipal Airport');
insert into AIRPORTS (code, name) values ('VPY', 'Chimoio Airport');
insert into AIRPORTS (code, name) values ('PCQ', 'Boun Neau Airport');
insert into AIRPORTS (code, name) values ('SQF', 'Solano Airport');
insert into AIRPORTS (code, name) values ('BBY', 'Bambari Airport');
insert into AIRPORTS (code, name) values ('EOR', 'El Dorado Airport');
insert into AIRPORTS (code, name) values ('SIR', 'Sion Airport');
insert into AIRPORTS (code, name) values ('SAE', 'Sangir Airport');
insert into AIRPORTS (code, name) values ('UVL', 'El Kharga Airport');
insert into AIRPORTS (code, name) values ('WGP', 'Umbu Mehang Kunda Airport');
insert into AIRPORTS (code, name) values ('PSD', 'Port Said Airport');
insert into AIRPORTS (code, name) values ('MDP', 'Mindiptana Airport');
insert into AIRPORTS (code, name) values ('KTV', 'Kamarata Airport');
insert into AIRPORTS (code, name) values ('NTU', 'Oceana Naval Air Station');
insert into AIRPORTS (code, name) values ('TIL', 'Cheadle Airport');
insert into AIRPORTS (code, name) values ('NDF', 'Ndalatandos Airport');
insert into AIRPORTS (code, name) values ('AUM', 'Austin Municipal Airport');
insert into AIRPORTS (code, name) values ('MLW', 'Spriggs Payne Airport');
insert into AIRPORTS (code, name) values ('JLN', 'Joplin Regional Airport');
insert into AIRPORTS (code, name) values ('CYX', 'Cherskiy Airport');
insert into AIRPORTS (code, name) values ('ETD', 'Etadunna Airport');
insert into AIRPORTS (code, name) values ('OIR', 'Okushiri Airport');
insert into AIRPORTS (code, name) values ('WRW', 'Warrawagine Airport');
insert into AIRPORTS (code, name) values ('RFA', 'Rafaï Airport');
insert into AIRPORTS (code, name) values ('QRO', 'Querétaro Intercontinental Airport');
insert into AIRPORTS (code, name) values ('GCC', 'Gillette Campbell County Airport');
insert into AIRPORTS (code, name) values ('CLH', 'Coolah Airport');
insert into AIRPORTS (code, name) values ('AGG', 'Angoram Airport');
insert into AIRPORTS (code, name) values ('PRG', 'Václav Havel Airport Prague');
insert into AIRPORTS (code, name) values ('PRK', 'Prieska Airport');
insert into AIRPORTS (code, name) values ('SYH', 'Syangboche Airport');
insert into AIRPORTS (code, name) values ('NAS', 'Lynden Pindling International Airport');
insert into AIRPORTS (code, name) values ('TBP', 'Capitan FAP Pedro Canga Rodriguez Airport');
insert into AIRPORTS (code, name) values ('BGH', 'Abbaye Airport');
insert into AIRPORTS (code, name) values ('AUO', 'Auburn University Regional Airport');
insert into AIRPORTS (code, name) values ('NGO', 'Chubu Centrair International Airport');
insert into AIRPORTS (code, name) values ('SVT', 'Savuti Airport');
insert into AIRPORTS (code, name) values ('OTD', 'Contadora Airport');
insert into AIRPORTS (code, name) values ('TMT', 'Trombetas Airport');
insert into AIRPORTS (code, name) values ('XZA', 'Zabré Airport');
insert into AIRPORTS (code, name) values ('NSM', 'Norseman Airport');
insert into AIRPORTS (code, name) values ('PAX', 'Port-de-Paix Airport');
insert into AIRPORTS (code, name) values ('VRI', 'Varandey Airport');
insert into AIRPORTS (code, name) values ('LRE', 'Longreach Airport');
insert into AIRPORTS (code, name) values ('PSR', 'Pescara International Airport');
insert into AIRPORTS (code, name) values ('NLP', 'Nelspruit Airport');
insert into AIRPORTS (code, name) values ('OVA', 'Bekily Airport');
insert into AIRPORTS (code, name) values ('SPN', 'Saipan International Airport');
insert into AIRPORTS (code, name) values ('NEF', 'Neftekamsk Airport');
insert into AIRPORTS (code, name) values ('DMU', 'Dimapur Airport');
insert into AIRPORTS (code, name) values ('FIG', 'Fria Airport');
insert into AIRPORTS (code, name) values ('PAY', 'Pamol Airport');
insert into AIRPORTS (code, name) values ('OHH', 'Okha Airport');
insert into AIRPORTS (code, name) values ('MLO', 'Milos Airport');
insert into AIRPORTS (code, name) values ('HEX', 'Herrera Airport');
insert into AIRPORTS (code, name) values ('BAU', 'Bauru Airport');
insert into AIRPORTS (code, name) values ('NIF', 'Camp Nifty Airport');
insert into AIRPORTS (code, name) values ('NYM', 'Nadym Airport');
insert into AIRPORTS (code, name) values ('CYT', 'Yakataga Airport');
insert into AIRPORTS (code, name) values ('UVF', 'Hewanorra International Airport');
insert into AIRPORTS (code, name) values ('SQN', 'Emalamo Sanana Airport');
insert into AIRPORTS (code, name) values ('BTK', 'Bratsk Airport');
insert into AIRPORTS (code, name) values ('GUF', 'Jack Edwards Airport');
insert into AIRPORTS (code, name) values ('SJZ', 'São Jorge Airport');
insert into AIRPORTS (code, name) values ('CIQ', 'Chiquimula Airport');
insert into AIRPORTS (code, name) values ('TXF', '9 de Maio - Teixeira de Freitas Airport');
insert into AIRPORTS (code, name) values ('AAC', 'El Arish International Airport');
insert into AIRPORTS (code, name) values ('0', 'São José Airport');
insert into AIRPORTS (code, name) values ('TET', 'Chingozi Airport');
insert into AIRPORTS (code, name) values ('STB', 'Santa Bárbara del Zulia Airport');
insert into AIRPORTS (code, name) values ('LEM', 'Lemmon Municipal Airport');
insert into AIRPORTS (code, name) values ('ANQ', 'Tri State Steuben County Airport');
insert into AIRPORTS (code, name) values ('RZA', 'Santa Cruz Airport');
insert into AIRPORTS (code, name) values ('TUF', 'Tours-Val-de-Loire Airport');
insert into AIRPORTS (code, name) values ('FEJ', 'Feijó Airport');
insert into AIRPORTS (code, name) values ('SYK', 'Stykkishólmur Airport');
insert into AIRPORTS (code, name) values ('SNE', 'Preguiça Airport');
insert into AIRPORTS (code, name) values ('HUF', 'Terre Haute Regional Airport, Hulman Field');
insert into AIRPORTS (code, name) values ('OSM', 'Mosul International Airport');
insert into AIRPORTS (code, name) values ('RWL', 'Rawlins Municipal Airport/Harvey Field');
insert into AIRPORTS (code, name) values ('IBO', 'Ibo Airport');
insert into AIRPORTS (code, name) values ('RZP', 'Cesar Lim Rodriguez Airport');
insert into AIRPORTS (code, name) values ('NND', 'Nangade Airport');
insert into AIRPORTS (code, name) values ('FRN', 'Bryant Army Heliport');
insert into AIRPORTS (code, name) values ('KSH', 'Shahid Ashrafi Esfahani Airport');
insert into AIRPORTS (code, name) values ('NUL', 'Nulato Airport');
insert into AIRPORTS (code, name) values ('YAG', 'Fort Frances Municipal Airport');
insert into AIRPORTS (code, name) values ('YQA', 'Muskoka Airport');
insert into AIRPORTS (code, name) values ('NAZ', 'Nana Airport');
insert into AIRPORTS (code, name) values ('LYU', 'Ely Municipal Airport');
insert into AIRPORTS (code, name) values ('ORN', 'Es Senia Airport');
insert into AIRPORTS (code, name) values ('YAR', 'La Grande-3 Airport');
insert into AIRPORTS (code, name) values ('ESM', 'General Rivadeneira Airport');
insert into AIRPORTS (code, name) values ('SOM', 'San Tomé Airport');
insert into AIRPORTS (code, name) values ('QNV', 'Aeroclube Airport');
insert into AIRPORTS (code, name) values ('EGL', 'Negele Airport');
insert into AIRPORTS (code, name) values ('CRT', 'Z M Jack Stell Field');
insert into AIRPORTS (code, name) values ('VAH', 'Capitán Av. Vidal Villagomez Toledo Airport');
insert into AIRPORTS (code, name) values ('NBA', 'Nambaiyufa Airport');
insert into AIRPORTS (code, name) values ('EUM', 'Neumünster Airport');
insert into AIRPORTS (code, name) values ('KCC', 'Coffman Cove Seaplane Base');
insert into AIRPORTS (code, name) values ('KPA', 'Kopiago Airport');
insert into AIRPORTS (code, name) values ('IKU', 'Issyk-Kul International Airport');
insert into AIRPORTS (code, name) values ('AIS', 'Arorae Island Airport');
insert into AIRPORTS (code, name) values ('URC', 'Ürümqi Diwopu International Airport');
insert into AIRPORTS (code, name) values ('YRR', 'Stuart Island Airstrip');
insert into AIRPORTS (code, name) values ('DBP', 'Debepare Airport');
insert into AIRPORTS (code, name) values ('HUQ', 'Hon Airport');
insert into AIRPORTS (code, name) values ('BHK', 'Bukhara Airport');
insert into AIRPORTS (code, name) values ('AGA', 'Al Massira Airport');
insert into AIRPORTS (code, name) values ('CBW', 'Campo Mourão Airport');
insert into AIRPORTS (code, name) values ('IOA', 'Ioannina Airport');
insert into AIRPORTS (code, name) values ('KPY', 'Port Bailey Seaplane Base');
insert into AIRPORTS (code, name) values ('OWK', 'Central Maine Airport of Norridgewock');
insert into AIRPORTS (code, name) values ('PAG', 'Pagadian Airport');
insert into AIRPORTS (code, name) values ('PKZ', 'Pakse International Airport');
insert into AIRPORTS (code, name) values ('DSS', 'Blaise Diagne International Airport');
insert into AIRPORTS (code, name) values ('NKC', 'Nouakchott–Oumtounsy International Airport');
insert into AIRPORTS (code, name) values ('RQO', 'El Reno Regional Airport');
insert into AIRPORTS (code, name) values ('GLO', 'Gloucestershire Airport');
insert into AIRPORTS (code, name) values ('SNP', 'St Paul Island Airport');
